// src/pages/Sign.tsx
import { useState, useEffect } from 'react'
import { useParams, useSearchParams, useNavigate, Link } from 'react-router-dom'
import { decode, resolveTransaction, resolveCallback, type ParsedSteemUri } from '@/lib/steem-uri'
import { broadcastTransaction } from '@/lib/steem'
import { useAuthStore } from '@/stores/auth'
import { getAuthority } from '@/lib/auth'
import type { KeysMap } from '@/lib/auth'

export function Sign() {
  const params = useParams()
  const [searchParams] = useSearchParams()
  const navigate = useNavigate()
  const pathMatch = params['*'] ?? ''
  const username = useAuthStore((s) => s.username)
  const keys = useAuthStore((s) => s.keys)
  const signTx = useAuthStore((s) => s.signTx)
  const authority = getAuthority(searchParams.get('authority') ?? undefined, 'active')
  const [parsed, setParsed] = useState<ParsedSteemUri | null>(null)
  const [uriValid, setUriValid] = useState(true)
  const [loading, setLoading] = useState(false)
  const [txId, setTxId] = useState<string | null>(null)
  const [failed, setFailed] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const uri = `steem://sign/${pathMatch}${searchParams.toString() ? `?${searchParams.toString()}` : ''}`

  useEffect(() => {
    let cancelled = false
    decode(uri)
      .then((p) => {
        if (!cancelled) {
          setParsed(p)
          setUriValid(true)
        }
      })
      .catch(() => {
        if (!cancelled) {
          setParsed(null)
          setUriValid(false)
        }
      })
    return () => {
      cancelled = true
    }
  }, [uri])

  const hasRequiredKey = username && ((keys as KeysMap)[authority as keyof KeysMap] ?? keys.active)

  async function handleApprove() {
    if (!parsed || !username) return
    setLoading(true)
    setFailed(false)
    setError(null)
    setTxId(null)
    try {
      const tx = await resolveTransaction(parsed, username)
      const signedTx = await signTx(tx, authority)
      const result = await broadcastTransaction(signedTx) as { id?: string; block_num?: number; txn_num?: number }
      setTxId(result?.id ?? null)
      setFailed(false)
      const callbackUrl = parsed.params?.callback as string | undefined
      if (callbackUrl && typeof callbackUrl === 'string') {
        const sig = (signedTx as { signatures?: string[] })?.signatures?.[0] ?? ''
        const redirectUrl = await resolveCallback(callbackUrl, {
          sig,
          id: result?.id,
          block: result?.block_num,
          txn: result?.txn_num,
        })
        window.location.href = redirectUrl
        return
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
      setFailed(true)
    }
    setLoading(false)
  }

  function handleReject() {
    navigate('/')
  }

  if (!uriValid || !parsed) {
    return (
      <div>
        <h1>Confirm transaction</h1>
        <p style={{ color: 'red' }}>Invalid signing URL.</p>
        <button type="button" onClick={() => navigate('/')}>
          Back
        </button>
      </div>
    )
  }

  if (txId && !failed) {
    return (
      <div>
        <h1>Transaction broadcast</h1>
        <p>Transaction ID: {txId}</p>
        <button type="button" onClick={() => navigate('/')}>
          Done
        </button>
      </div>
    )
  }

  return (
    <div>
      <h1>Confirm transaction {authority ? `(${authority})` : ''}</h1>
      {parsed?.tx && (
        <pre style={{ fontSize: 12, overflow: 'auto', maxHeight: 300 }}>
          {JSON.stringify(parsed.tx, null, 2)}
        </pre>
      )}
      {!username || !hasRequiredKey ? (
        <p>
          <Link to={`/login?redirect=${encodeURIComponent(uri)}&authority=${authority}`}>
            Continue to login
          </Link>
        </p>
      ) : (
        <>
          {parsed.params?.callback && (
            <p>You will be redirected after signing.</p>
          )}
          {error != null && <p style={{ color: 'red' }}>{error}</p>}
          <div style={{ display: 'flex', gap: 8 }}>
            <button type="button" onClick={handleApprove} disabled={loading}>
              {parsed.params?.no_broadcast ? 'Sign' : 'Approve'}
            </button>
            <button type="button" onClick={handleReject}>
              Cancel
            </button>
          </div>
        </>
      )}
    </div>
  )
}

// legacy/src/views/Sign.vue
<template>
  <div>
    <Header :title="title" />
    <div v-if="parsed && uriIsValid" class="p-4 after-header">
      <div class="container-sm mx-auto">
        <!-- <OpenExternal
          v-if="isWeb && !failed && !transactionId"
          :withChrome="true"
          :uri="uri"
          class="hide-sm"
        />-->
        <Error v-if="!loading && failed" :error="error" />
        <Confirmation v-if="!loading && !!transactionId" :id="transactionId" />
        <div v-if="!failed && !transactionId">
          <Operation
            v-for="(operation, key) in parsed.tx.operations"
            :operation="operation"
            :key="key"
          />
          <div class="flash flash-warn mb-4" v-if="parsed.params.callback">
            You are going to get redirected to
            <span class="link-color">{{ $filters.parseUrl(parsed.params.callback) }}</span
            >.
          </div>
          <div class="flash flash-warn mb-4" v-if="username && hasRequiredKey === false">
            This transaction requires your <b>{{ authority }}</b> key.
          </div>
          <div class="mb-4">
            <router-link
              :to="{ name: 'login', query: { redirect: this.$route.fullPath, authority } }"
              class="btn btn-large btn-blue mr-2 mb-2"
              v-if="!username || hasRequiredKey === false"
            >
              Continue
            </router-link>
            <button
              type="submit"
              class="btn btn-large btn-success mr-2 mb-2"
              :disabled="loading"
              @click="handleSubmit"
              v-else
            >
              {{ parsed.params.no_broadcast ? 'Sign' : 'Approve' }}
            </button>
            <button class="btn btn-large mb-2" @click="handleReject">
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="p-4 after-header" v-else>
      <div class="container-sm mx-auto flash flash-error mb-4">
        Oops, something went wrong. The signing URL provided is invalid.
      </div>
    </div>
  </div>
</template>

<script>
import * as steemuri from 'steem-uri';
import { mapActions } from 'vuex';
import { resolveTransaction } from '@/helpers/client';
import { getAuthority } from '@/helpers/auth';
import {
  isWeb,
  isChromeExtension,
  isElectron,
  getVestsToSP,
  legacyUriToParsedSteemUri,
  getLowestAuthorityRequired,
  processTransaction,
  buildSearchParams,
  signComplete,
  REQUEST_ID_PARAM,
} from '@/helpers/utils';

export default {
  data() {
    return {
      parsed: null,
      uriIsValid: true,
      loading: false,
      transactionId: '',
      failed: false,
      error: false,
      isWeb: isWeb(),
      uri: `steem://sign/${this.$route.params.pathMatch}${buildSearchParams(this.$route)}`,
      requestId: this.$route.query[REQUEST_ID_PARAM],
      authority: getAuthority(this.$route.query.authority),
      hasRequiredKey: null,
    };
  },
  computed: {
    title() {
      let title = 'Confirm transaction';
      if (this.authority) title += ` (${this.authority})`;
      return title;
    },
    username() {
      return this.$store.state.auth.username;
    },
    config() {
      return {
        vestsToSP: getVestsToSP(this.$store.state.settings.properties),
      };
    },
  },
  mounted() {
    this.parseUri(this.uri);
    if (!this.authority && this.parsed && this.parsed.tx) {
      this.authority = getLowestAuthorityRequired(this.parsed.tx);
      this.hasRequiredKey = !!(
        this.$store.state.auth.username && this.$store.state.auth.keys[this.authority]
      );
    }
  },
  methods: {
    ...mapActions(['sign', 'broadcast']),
    parseUri(uri) {
      let parsed;
      try {
        parsed = steemuri.decode(uri);
      } catch (err) {
        parsed = legacyUriToParsedSteemUri(uri);
        if (!parsed) {
          this.uriIsValid = false;
        }
      }
      this.parsed = processTransaction(parsed, this.config);
    },
    async handleSubmit() {
      this.loading = true;
      let sig = null;
      let tx = null;
      let signedTx = null;
      let confirmation = null;

      try {
        tx = await resolveTransaction(this.parsed, this.$store.state.auth.username);
        signedTx = await this.sign({ tx, authority: this.authority });
        [sig] = signedTx.signatures;
      } catch (err) {
        console.error('Failed to resolve and sign transaction', err);
      }

      if (!sig) {
        this.transactionId = '';
        this.failed = true;
        this.loading = false;
        return;
      }

      if (!this.parsed.params.no_broadcast) {
        try {
          confirmation = await this.broadcast(signedTx);
          this.transactionId = confirmation.id;
          this.failed = false;

          if (this.requestId) {
            signComplete(this.requestId, null, { result: confirmation });
          }
        } catch (err) {
          this.error = err;
          console.error('Failed to broadcast transaction', err);
          this.transactionId = '';
          this.failed = true;

          if (this.requestId) {
            signComplete(this.requestId, err, null);
          }
        }
      }

      // Handle redirect for web, Chrome extension, and desktop app
      if (confirmation && this.parsed.params.callback && isWeb()) {
        window.location = steemuri.resolveCallback(this.parsed.params.callback, {
          sig,
          id: confirmation.id || undefined,
          block: confirmation.block_num || undefined,
          txn: confirmation.txn_num || undefined,
        });
      } else if (isChromeExtension() || isElectron()) {
        // Chrome extension and Electron app redirect is handled by signComplete callback
        this.loading = false;
      } else {
        this.loading = false;
      }
    },
    handleReject() {
      if (this.requestId) {
        signComplete(this.requestId, 'Request rejected', null);
      }
      if (!isChromeExtension()) {
        this.$router.push('/');
      }
    },
  },
};
</script>
